name: Build with DevkitPro
on:
  push:
  workflow_dispatch:
jobs:
  wii:
    name: Build Wii
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup grrlib
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITPPC=${DEVKITPRO}/devkitPPC
          dkp-pacman -Syu
          dkp-pacman -Sy devkitPPC libogc
          git clone https://github.com/GRRLIB/GRRLIB.git
          cd GRRLIB
          make
          mkdir -p $DEVKITPRO/portlibs/ppc/
          cp libGRRLIB.a $DEVKITPRO/portlibs/ppc/
          cp -r GRRLIB $DEVKITPRO/portlibs/ppc/include/
      - name: Build all wii projects
        run: |
            export DEVKITPRO=/opt/devkitpro
            export DEVKITPPC=${DEVKITPRO}/devkitPPC
            rootpwd=$(pwd)
            for d in */; do 
              echo "$d"
              cd "$d"
              make clean
              make
              cp *.dol ../
              cp *.elf ../
              cp *.bin ../
              cd "$rootpwd"
            done
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: wii-build
            path: |
                ./*.dol
                ./*.elf
                ./*.bin
